local binds = require("binds")
local monitors = require("monitors")
local appearance = require("appearance")
local autostart = require("autostart")
local animations = require("animations")

hl.config({
    autogenerated = false,
})
